<?php

namespace App\Livewire\Admin;

use App\Models\User;
use App\Models\Role;
use Livewire\Component;
use Livewire\WithPagination;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Flux;

class UserManager extends Component
{
    use WithPagination;

    public $search = '';
    public $roleFilter = '';
    public $statusFilter = '';
    public $sortBy = 'created_at';
    public $sortDirection = 'desc';

    public $readyToLoad = false;

    public function load()
    {
        $this->readyToLoad = true;
    }

    // Create/Edit User Form
    public $userId;
    public $name;
    public $username;
    public $email;
    public $password;
    public $is_active = true;
    public $selectedRoles = [];

    // Modals
    public $showCreateModal = false;
    public $showEditModal = false;
    public $showResetPasswordModal = false;

    // Password Visibility
    public $showPassword = false;
    public $autoGeneratedPassword = '';

    protected $queryString = ['search', 'roleFilter', 'statusFilter', 'sortBy', 'sortDirection'];

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function createUser()
    {
        if (!auth()->user()?->isAdmin()) abort(403);
        $this->resetForm();
        $this->showPassword = true; // Show password by default when creating
        $this->password = Str::random(12); // Pre-fill with a secure random password
        $this->showCreateModal = true;
    }

    public function saveUser()
    {
        if (!auth()->user()?->isAdmin()) abort(403);
        $this->validate([
            'name' => 'required|string|max:255',
            'username' => 'required|string|max:255|unique:users,username',
            'email' => 'required|email|max:255|unique:users,email',
            'password' => 'required|string|min:8',
            'selectedRoles' => 'required|array|min:1',
        ]);

        $user = User::create([
            'name' => $this->name,
            'username' => $this->username,
            'email' => $this->email,
            'password' => Hash::make($this->password),
            'is_active' => $this->is_active,
            'email_verified_at' => now(), // Assume admin created users are verified
        ]);

        $user->roles()->sync($this->selectedRoles);

        $this->showCreateModal = false;
        Flux::toast(variant: 'success', heading: 'Berhasil', text: 'Pengguna baru telah dibuat.');
        $this->resetForm();
    }

    public function editUser($id)
    {
        if (!auth()->user()?->isAdmin()) abort(403);
        $this->resetForm();
        $user = User::findOrFail($id);
        $this->userId = $user->id;
        $this->name = $user->name;
        $this->username = $user->username;
        $this->email = $user->email;
        $this->is_active = $user->is_active;
        $this->selectedRoles = $user->roles->pluck('id')->toArray();
        $this->showEditModal = true;
    }

    public function updateUser()
    {
        if (!auth()->user()?->isAdmin()) abort(403);
        $this->validate([
            'name' => 'required|string|max:255',
            'username' => 'required|string|max:255|unique:users,username,' . $this->userId,
            'email' => 'required|email|max:255|unique:users,email,' . $this->userId,
            'selectedRoles' => 'required|array|min:1',
        ]);

        $user = User::findOrFail($this->userId);
        $user->update([
            'name' => $this->name,
            'username' => $this->username,
            'email' => $this->email,
            'is_active' => $this->is_active,
        ]);

        $user->roles()->sync($this->selectedRoles);

        $this->showEditModal = false;
        Flux::toast(variant: 'success', heading: 'Berhasil', text: 'Data pengguna telah diperbarui.');
    }

    public function toggleUserStatus($id)
    {
        if (!auth()->user()?->isAdmin()) abort(403);
        $user = User::findOrFail($id);
        $user->is_active = !$user->is_active;
        $user->save();
        Flux::toast(variant: 'success', heading: 'Berhasil', text: 'Status pengguna telah diubah.');
    }

    public function initiatePasswordReset($id)
    {
        if (!auth()->user()?->isAdmin()) abort(403);
        $this->userId = $id;
        $this->autoGeneratedPassword = Str::random(12);
        $this->showResetPasswordModal = true;
    }

    public function resetPassword()
    {
        if (!auth()->user()?->isAdmin()) abort(403);
        $user = User::findOrFail($this->userId);
        $user->password = Hash::make($this->autoGeneratedPassword);
        $user->save();

        $this->showResetPasswordModal = false;
        Flux::toast(variant: 'success', heading: 'Berhasil', text: 'Password pengguna telah direset.');
    }

    private function resetForm()
    {
        $this->userId = null;
        $this->name = '';
        $this->username = '';
        $this->email = '';
        $this->password = '';
        $this->is_active = true;
        $this->selectedRoles = [];
        $this->showPassword = false;
        $this->autoGeneratedPassword = '';
    }

    public function render()
    {
        if (!$this->readyToLoad) {
            return view('livewire.admin.user-manager', [
                'users' => User::whereRaw('1 = 0')->paginate(10),
                'roles' => Role::all(),
            ]);
        }

        $query = User::query()->with('roles');

        if ($this->search) {
            $query->where(function($q) {
                $q->where('name', 'like', '%' . $this->search . '%')
                  ->orWhere('email', 'like', '%' . $this->search . '%')
                  ->orWhere('username', 'like', '%' . $this->search . '%');
            });
        }

        if ($this->roleFilter) {
            $query->whereHas('roles', function($q) {
                $q->where('slug', $this->roleFilter);
            });
        }

        if ($this->statusFilter !== '') {
            $query->where('is_active', $this->statusFilter);
        }

        $allowedSorts = ['name', 'email', 'username', 'created_at', 'is_active'];
        $sort = in_array($this->sortBy, $allowedSorts) ? $this->sortBy : 'created_at';
        $direction = in_array(strtolower($this->sortDirection), ['asc', 'desc']) ? $this->sortDirection : 'desc';

        return view('livewire.admin.user-manager', [
            'users' => $query->orderBy($sort, $direction)->paginate(10),
            'roles' => Role::all(),
        ]);
    }
}
